  INSERT INTO T_FILE (POST_NUMBER, FILENAME)
    VALUES (5,dsadsa);
    
    CREATE SEQUENCE post_number_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
DROP SEQUENCE post_number_seq;